<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7IBMVUC" failures="3" tests="6" name="Test1" time="66.363" errors="0" timestamp="12 Jun 2019 15:37:55 GMT">
  <testcase classname="com.nopcommerce.testCases.TC_LoginTest_001" name="loginTest" time="11.637"/>
  <testcase classname="com.nopcommerce.testCases.TC_LoginDDT_002" name="loginTest" time="9.712"/>
  <testcase classname="com.nopcommerce.testCases.TC_LoginDDT_002" name="loginTest" time="3.919">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopcommerce.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:40)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.nopcommerce.testCases.TC_LoginDDT_002" name="loginTest" time="3.956">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopcommerce.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:40)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.nopcommerce.testCases.TC_LoginDDT_002" name="loginTest" time="3.768">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopcommerce.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:40)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.nopcommerce.testCases.TC_AddCustomerTest_003" name="addNewCustomer" time="16.095"/>
</testsuite> <!-- Test1 -->
